import type { ThemeConfig, ThemeKey } from "./types";

export const THEMES: Record<ThemeKey, ThemeConfig> = {
  undervalued_growth: {
    key: "undervalued_growth",
    label: "저평가 성장주",
    shortLabel: "저평가 성장",
    description: "PEG < 1.0이면서 매출 성장률이 높은 종목. 성장 대비 저평가된 황금 기회.",
    criteria: ["PEG < 1.0", "매출성장률 > 15%", "리스크 가드 통과"],
    color: "#00d17a",
    icon: "🌱",
  },
  growth_momentum: {
    key: "growth_momentum",
    label: "성장 기대주",
    shortLabel: "모멘텀",
    description: "최근 3개 분기 연속 YoY 영업이익 가속화 중인 종목.",
    criteria: ["3분기 연속 영업이익 YoY 증가", "가속화 추세", "리스크 가드 통과"],
    color: "#1e90ff",
    icon: "🚀",
  },
  safe_growth: {
    key: "safe_growth",
    label: "안전 성장주",
    shortLabel: "안전 성장",
    description: "5년 연속 이익 성장과 낮은 부채비율을 동시에 만족하는 방어적 성장주.",
    criteria: ["5년 연속 이익 성장", "부채비율 < 50%", "리스크 가드 통과"],
    color: "#2ed573",
    icon: "🛡️",
  },
  deep_value: {
    key: "deep_value",
    label: "저렴한 평가주",
    shortLabel: "딥 밸류",
    description: "PBR 1.0 미만의 자산 대비 저평가 종목. 순자산 이하로 거래되는 가치주.",
    criteria: ["PBR < 1.0", "순현금 보유 우량", "리스크 가드 통과"],
    color: "#ffa502",
    icon: "💎",
  },
  high_roe: {
    key: "high_roe",
    label: "고수익 저평가",
    shortLabel: "고 ROE",
    description: "높은 자기자본이익률(ROE > 15%)에도 불구하고 PER 15 미만으로 저평가된 종목.",
    criteria: ["ROE > 15%", "PER < 15", "리스크 가드 통과"],
    color: "#ff6b81",
    icon: "📈",
  },
  breakout: {
    key: "breakout",
    label: "저평가 탈출",
    shortLabel: "브레이크아웃",
    description: "200일 이동평균선을 돌파하고 정배열로 전환 중인 기술적 상승 신호.",
    criteria: ["200일선 상향 돌파", "정배열 전환 (50MA > 200MA)", "리스크 가드 통과"],
    color: "#eccc68",
    icon: "⚡",
  },
  bugatti: {
    key: "bugatti",
    label: "부가티주",
    shortLabel: "최상위",
    description: "영업이익률 30% 이상의 압도적인 수익 창출 능력을 보유한 Top-Tier 기업.",
    criteria: ["영업이익률 > 30%", "시장 지배력 최상위", "리스크 가드 통과"],
    color: "#a29bfe",
    icon: "🏎️",
  },
  dividend: {
    key: "dividend",
    label: "배당주",
    shortLabel: "배당",
    description: "배당수익률 4% 이상과 안정적 현금흐름을 보유한 인컴 투자 적합 종목.",
    criteria: ["배당수익률 > 4%", "안정적 FCF", "리스크 가드 통과"],
    color: "#fd79a8",
    icon: "💰",
  },
  dividend_aristocrat: {
    key: "dividend_aristocrat",
    label: "미래왕 배당주",
    shortLabel: "배당귀족",
    description: "10년 이상 연속 배당금을 증액한 배당 귀족주. 장기 인컴 투자의 정석.",
    criteria: ["10년 이상 연속 배당 증가", "Dividend Aristocrat", "리스크 가드 통과"],
    color: "#fdcb6e",
    icon: "👑",
  },
};

export const THEME_KEYS = Object.keys(THEMES) as ThemeKey[];
